// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MT.DataManagement.Teams.AzureSql;
using System;

namespace MT.DataManagement.Teams.AzureSql.Migrations
{
    [DbContext(typeof(MilestoneAnalyticsDataContext))]
    [Migration("20180405045526_Setup_Keys")]
    partial class Setup_Keys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.CostMarker", b =>
                {
                    b.Property<string>("CostMarkerId");

                    b.Property<string>("TeamId");

                    b.Property<double>("Factor");

                    b.HasKey("CostMarkerId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("CostMarker");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Member", b =>
                {
                    b.Property<string>("MemberId");

                    b.Property<string>("TeamId");

                    b.Property<bool>("IncludeInReports");

                    b.HasKey("MemberId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Repo", b =>
                {
                    b.Property<string>("RepoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TeamId");

                    b.HasKey("RepoId");

                    b.HasIndex("TeamId");

                    b.ToTable("Repo");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DefaultMilestonesToTrack");

                    b.Property<string>("MemberId");

                    b.Property<string>("MemberTeamId");

                    b.Property<string>("Organization");

                    b.Property<string>("RepoId");

                    b.HasKey("TeamId");

                    b.HasIndex("RepoId");

                    b.HasIndex("MemberId", "MemberTeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.CostMarker", b =>
                {
                    b.HasOne("MT.DataManagement.Teams.AzureSql.Model.Team")
                        .WithMany("CostMarkers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Member", b =>
                {
                    b.HasOne("MT.DataManagement.Teams.AzureSql.Model.Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Repo", b =>
                {
                    b.HasOne("MT.DataManagement.Teams.AzureSql.Model.Team")
                        .WithMany("Repos")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Team", b =>
                {
                    b.HasOne("MT.DataManagement.Teams.AzureSql.Model.Repo")
                        .WithMany("Teams")
                        .HasForeignKey("RepoId");

                    b.HasOne("MT.DataManagement.Teams.AzureSql.Model.Member")
                        .WithMany("Teams")
                        .HasForeignKey("MemberId", "MemberTeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
