// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MT.DataManagement.Teams.AzureSql;
using System;

namespace MT.DataManagement.Teams.AzureSql.Migrations
{
    [DbContext(typeof(MilestoneAnalyticsDataContext))]
    [Migration("20180328144831_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.CostMarker", b =>
                {
                    b.Property<string>("CostMarkerId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Factor");

                    b.Property<string>("TeamId");

                    b.HasKey("CostMarkerId");

                    b.HasIndex("TeamId");

                    b.ToTable("CostMarker");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Member", b =>
                {
                    b.Property<string>("MemberId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TeamId");

                    b.HasKey("MemberId");

                    b.HasIndex("TeamId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Repo", b =>
                {
                    b.Property<string>("RepoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TeamId");

                    b.HasKey("RepoId");

                    b.HasIndex("TeamId");

                    b.ToTable("Repo");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DefaultMilestonesToTrack");

                    b.Property<string>("MemberId");

                    b.Property<string>("Organization");

                    b.HasKey("TeamId");

                    b.HasIndex("MemberId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.CostMarker", b =>
                {
                    b.HasOne("MT.DataManagement.Teams.AzureSql.Model.Team")
                        .WithMany("CostMarkers")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Member", b =>
                {
                    b.HasOne("MT.DataManagement.Teams.AzureSql.Model.Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Repo", b =>
                {
                    b.HasOne("MT.DataManagement.Teams.AzureSql.Model.Team")
                        .WithMany("Repos")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("MT.DataManagement.Teams.AzureSql.Model.Team", b =>
                {
                    b.HasOne("MT.DataManagement.Teams.AzureSql.Model.Member")
                        .WithMany("Teams")
                        .HasForeignKey("MemberId");
                });
#pragma warning restore 612, 618
        }
    }
}
